server:
  port: 8890
  servlet:
    context-path: /first

spring:
  main:
    banner-mode: off

kafka:
  bootstrap-servers: *
  #  bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
  group-id: *
  password: *

