// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.first.family.rmq.msgproto;

public final class AMQPMessageProto {
  private AMQPMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amqp_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amqp_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\004amqp\032\013model.proto\"^\n\007Me" +
      "ssage\022\022\n\napiVersion\030\001 \001(\t\022\013\n\003qos\030\002 \001(\005\022!" +
      "\n\010metadata\030\003 \001(\0132\017.model.Metadata\022\017\n\007mes" +
      "sage\030\004 \001(\014B3\n\035com.first.family.rmq.msgpr" +
      "otoB\020AMQPMessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.first.family.rmq.msgproto.ModelProto.getDescriptor(),
        });
    internal_static_amqp_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amqp_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amqp_Message_descriptor,
        new java.lang.String[] { "ApiVersion", "Qos", "Metadata", "Message", });
    com.first.family.rmq.msgproto.ModelProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
