// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.first.family.rmq.msgproto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amqp.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * message format version, current is 'v1'
   * </pre>
   *
   * <code>string apiVersion = 1;</code>
   * @return The apiVersion.
   */
  java.lang.String getApiVersion();
  /**
   * <pre>
   * message format version, current is 'v1'
   * </pre>
   *
   * <code>string apiVersion = 1;</code>
   * @return The bytes for apiVersion.
   */
  com.google.protobuf.ByteString
      getApiVersionBytes();

  /**
   * <pre>
   * message qos 0
   * </pre>
   *
   * <code>int32 qos = 2;</code>
   * @return The qos.
   */
  int getQos();

  /**
   * <pre>
   * metadata for the message
   * </pre>
   *
   * <code>.model.Metadata metadata = 3;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * metadata for the message
   * </pre>
   *
   * <code>.model.Metadata metadata = 3;</code>
   * @return The metadata.
   */
  com.first.family.rmq.msgproto.Metadata getMetadata();
  /**
   * <pre>
   * metadata for the message
   * </pre>
   *
   * <code>.model.Metadata metadata = 3;</code>
   */
  com.first.family.rmq.msgproto.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * user specified message
   * </pre>
   *
   * <code>bytes message = 4;</code>
   * @return The message.
   */
  com.google.protobuf.ByteString getMessage();
}
