// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.first.family.rmq.msgproto;

public interface MetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.Metadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  The unique id for the message
   * </pre>
   *
   * <code>string uid = 1;</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <pre>
   *  The unique id for the message
   * </pre>
   *
   * <code>string uid = 1;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <pre>
   * The creation timestamp of the message
   * </pre>
   *
   * <code>int64 createTime = 2;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   * The tags of the message
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 3;</code>
   */
  int getLabelsCount();
  /**
   * <pre>
   * The tags of the message
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 3;</code>
   */
  boolean containsLabels(
      java.lang.String key);
  /**
   * Use {@link #getLabelsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getLabels();
  /**
   * <pre>
   * The tags of the message
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getLabelsMap();
  /**
   * <pre>
   * The tags of the message
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 3;</code>
   */
  /* nullable */
java.lang.String getLabelsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * The tags of the message
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 3;</code>
   */
  java.lang.String getLabelsOrThrow(
      java.lang.String key);
}
